### PR TITLE
fix: 🩹 use unified keywords(PUBLIC_ENV_KEY)

### PR DESCRIPTION
**Pull request by sunrabbit123**

### CODE REVIEW

**Review by HofmannZ — CHANGES_REQUESTED** [review]
Thank you for the contribution @sunrabbit123! 🙏

One minor change request, can you change the commit message to use the conventional commit style: https://www.conventionalcommits.org/en/v1.0.0/?

For example:

```sh
git commit --amend -m "fix: 🩹 use unified keywords(PUBLIC_ENV_KEY)"
git push --force-with-lease
```

**Comment by sunrabbit123** [comment]
thank you, I applied this

**Review by HofmannZ — APPROVED** [review]

**Comment by HofmannZ** [comment]
@sunrabbit123, could you perform a quick rebase? We've realized that GitHub Actions weren't set up to run for external contributors.

**Comment by sunrabbit123** [comment]
What should I do?
I didn't understand what a quick rebase is
@HofmannZ

**Comment by HofmannZ** [comment]
@sunrabbit123, my apologies for the confusion. What I meant was, could you please rebase your branch against `expatfile:development`?

**Comment by sunrabbit123** [comment]
@HofmannZ 

Fortunately, I understood.
Should I do it like this?

**Comment by sunrabbit123** [comment]
Or... should I open the pr again?

**Comment by HofmannZ** [comment]
This is fine thank you!

**Comment by HofmannZ** [comment]
@sunrabbit123 - Could you address the linting issues and any failing tests?

To check this on your end, you can run `pnpm lint` and `pnpm test --coverage` locally.

**Comment by sunrabbit123** [comment]
There was a typo like that
I revised it and uploaded it again.

**Comment by HofmannZ** [comment]
LGTM

**Pull request merged**
